        
	
	<div id="docbook_content_sidebar">
		 <h2 class="smalltitle">Software Links</h2>
           <dl class="leftColumn">
		   		<dt><a href="/toolkit/docs/5.2/5.2.5/Usage_Stats.html">Usage Statistics</a></dt>
				<dt><a href="/toolkit/docs/5.2/5.2.5/rn/">Release Notes</a></dt>
				<dt><a href="/toolkit/versioning.html">Versioning</a></dt>
				<dt><a href="/toolkit/downloads/">Downloads</a></dt>
				<dt><a href="/toolkit/advisories.html">Advisories</a></dt>
				<dt><a href="/toolkit/docs/5.2/5.2.5/licenses/">Licenses</a></dt>
				<dt><a href="http://dev.globus.org/wiki/How_to_contribute">CVS &amp; Dev Tools</a></dt>
			</dl>
			
		<h2 class="smalltitle">Getting Started</h2>
			<dl class="leftColumn">
			<!--
				<dt><a href="/toolkit/docs/5.2/5.2.5/doc_overview.html">Doc Structure</a></dt>
				-->
				<dt><a href="/toolkit/docs/5.2/5.2.5/admin/install/">Installing GT</a></dt>
				<dt><a href="/toolkit/docs/5.2/5.2.5/admin/quickstart/">Quickstart</a></dt>
				<dt><a href="/toolkit/docs/5.2/5.2.5/admin/install/#gtadmin-platform">Platform Notes</a></dt>
				<dt><a href="/toolkit/docs/5.2/5.2.5/appendices/developer/">GT Developer's Guide</a></dt>
	<!--			<dt><a href="/toolkit/docs/5.2/5.2.5/appendices/user/">GT User's Guide</a></dt> -->
				<dt><a href="/toolkit/docs/5.2/5.2.5/appendices/mig/">Migrating Guides</a></dt>
			</dl>
			
		<h2 class="smalltitle">Components</h2>
			<h2 class="smalltitle"></h2>
			<dl class="leftColumn">
			<dt>Data Management
			<dd><a href="/toolkit/docs/5.2/5.2.5/gridftp/">GridFTP</a></dd>
			</dt>
			<dt>Jobs Management
			<dd><a href="/toolkit/docs/5.2/5.2.5/gram5/">GRAM5</a></dd>
			</dt>
			<dt>Security
			<dd><a href="/toolkit/docs/5.2/5.2.5/gsic/">GSI C</a></dd>
				<dd><a href="/toolkit/docs/5.2/5.2.5/myproxy/">MyProxy</a></dd>
				<dd><a href="/toolkit/docs/5.2/5.2.5/gsiopenssh/">GSI-OpenSSH</a></dd>
				<dd><a href="/toolkit/docs/5.2/5.2.5/simpleca/">SimpleCA</a></dd>
			</dt>
			<dt>Common Runtime
				<dd><a href="/toolkit/docs/5.2/5.2.5/xio/">XIO</a></dd>
				<dd><a href="/toolkit/docs/5.2/5.2.5/ccommonlib/">C Common Libraries</a></dd>
			</dt>
			</dl>
	
			
		<h2 class="smalltitle">Reference</h2>
			<dl class="leftColumn">
			<!--	<dt><a href="/toolkit/docs/5.2/5.2.5/developer/#gt-bestpractices">Best Practices</a></dt> -->
				<dt><a href="/toolkit/docs/development/coding_guidelines.html">Coding Guidelines</a></dt>
				<dt><a href="/api/">API docs</a></dt>
				<dt><a href="/toolkit/docs/5.2/5.2.5/appendices/commands/">GT Commands</a></dt>
		<!--		<dt><a href="/toolkit/docs/5.2/5.2.5/appendices/user/#public-interfaces">Public Interfaces</a></dt> -->
				<dt><a href="/toolkit/docs/5.2/5.2.5/index.html#glossary">Glossary</a></dt>
			</dl>
	
	</div>
