        	<!-- content ENDS here -->
		</div>
      <!--ending div of container-->
    </div>
    <div class="clearing">&nbsp;</div>
    <!--ending div of wrapper-->
    <br/>
  </div>
<div id="footer">

  
  <p>Comments?<br />
  For questions or feedback about this website:  <a href="mailto:webmaster@globus.org">webmaster@globus.org</a><br />
  For technical support or questions about Globus software, visit our <a href="http://www.globus.org/toolkit/support.html">technical
support</a> page.
</p>
  <p>Globus Project and Globus Toolkit are trademarks<br />
    held by the University of Chicago</p>
  <!--ending div of footer-->
  <p>&nbsp;</p>
</div>
 <script src="http://www.google-analytics.com/urchin.js"
 type="text/javascript">
 </script>
 <script type="text/javascript">
 _uacct = "UA-726125-2";
 _udn="globus.org"; 
 urchinTracker();
 </script> 
</body>
</html>
