default: all

PDF_FILES = ccommonlib.pdf
SUBDIRS=admin developer mig pi qp rn

PDFS=admin/ccommonlibAdminGuide.pdf developer/ccommonlibDevelopersGuide.pdf mig/ccommonlibMigratingGuide.pdf qp/ccommonlibQualityProfile.pdf rn/ccommonlibReleaseNotes.pdf

ccommonlib.pdf: $(PDFS)

TOPDIR=..
include $(TOPDIR)/rules.mk
