<?php

$title = "Globus: Guidelines for Research Citations";
$section = "section-2";
include_once( "../../include/local.inc" );
include_once( $SITE_PATHS["SERV_INC"].'header.inc' ); 
?>
<!--
<div id="left">
<?php include($SITE_PATHS["SERV_INC"].'alliance.inc'); ?>
</div>
-->

<div id="main">

<h1 class="first">Guidelines for Reseach Paper Citations on the Globus Website</h1>

<p>For papers listed on this site, at least one author should be a member 
of the Globus Alliance.</p>

<p>The Globus Alliance manages its bibliography using the BibTeX tool. 
If you use BibTeX, you may download our <a href="globusbib.bib">citation 
database</a>. Note that this citation database is incomplete. (If not, 
you can still <a href="publications.php">view the citations</a> here online.)</p>

<p>If you have (or are aware of) appropriate publications that are not here, 
please submit them to <a href="mailto:webmaster@globus.org">webmaster@globus.org</a> 
using the BibTeX templates below.</p>

<h2>Acknowledging Sponsors</h2>

      <p>Publications describing work conducted in the Argonne 
    Mathematics and Computer Science Division should include the following 
    acknowledgement.</p>
    
<blockquote>
      This work was supported by the Mathematical, Information, and 
      Computational Sciences Division subprogram of the Office of Advanced 
      Scientific Computing Research, Office of Science, U.S. Department of 
      Energy, under Contract W-31-109-ENG-38.
</blockquote>

    <p>Work supported by NSF should include the following acknowledgement.</p>

    <blockquote>
    This material is based upon work supported by the National Science 
    Foundation under Grant No. (enter NSF grant number).
    </blockquote>

<h2>Templates for Bibliographic Citation</h2>
    <p>The following templates may be used for submitting bibliographic references to the Globus Alliance.</p>
    <p>Please select an appropriate document type, complete the corresponding template, and
    send the resulting reference to Julie Wulf (see above). It would be helpful if you
    could also mention the classification that you believe the publication falls under (e.g.,
    Overview Paper, Globus Toolkit Components, Higher-Level Services and Tools, Applications,
    or Other Globus-Related Research). </p>

<p>The three general types of entries are Articles (published in
    journals--use @Article), Tech Reports (ANL published reports, for example--use
    @TechReport) and Articles (published in Proceedings--use @InProceedings). </p>
 <p>Please complete each field between the { } marks and do not put commas between
    author names (for example, use &quot;John Bresnahan and Gregor von Laszewski and Julie
    Wulf&quot; instead of &quot;John Bresnahan, Gregor von Laszewski, and Julie Wulf&quot;)</p>
    <p>A keyword will be assigned to each entry, which will most likely be generated by the
    following rule: &quot;Globus&quot; + first three letters of first three authors + year ( +
    letter if the previous is not unique)</p>

    <p>Fields labelled OPT** are optional, and need not be completed, all other fields are
    required. Nevertheless, we ask that for the three types mentioned above, please
    complete as many fields as you can.</p>

    <hr>
    <p>@Article{,<br>
    author =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    title =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>

    journal =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    year =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTkey =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTvolume =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>

    OPTnumber =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTpages =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTmonth =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTnote =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>

    OPTannote =&nbsp;&nbsp;&nbsp;&nbsp; {}<br>
    }</p>
    <hr>
    <p>@InProceedings{,<br>
    author =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>

    title =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    booktitle =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTcrossref = {},<br>
    OPTkey =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>

    OPTpages =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTyear =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTeditor =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTvolume =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>

    OPTnumber =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTseries =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTaddress =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTmonth =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>

    OPTorganization = {},<br>
    OPTpublisher = {},<br>
    OPTnote =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTannote =&nbsp;&nbsp;&nbsp;&nbsp; {}<br>
    }</p>

    <hr>
    <p>@TechReport{,<br>
    author =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    title =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    institution = {},<br>

    year =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTkey =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTtype =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTnumber =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>

    OPTaddress =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTmonth =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTnote =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTannote =&nbsp;&nbsp;&nbsp;&nbsp; {}<br>

    }</p>
    <hr>
    <p>@InCollection{,<br>
    author =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    title =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>

    booktitle =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTcrossref = {},<br>
    OPTkey =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTpages =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>

    OPTpublisher = {},<br>
    OPTyear =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTeditor =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTvolume =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>

    OPTnumber =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTseries =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTtype =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTchapter =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>

    OPTaddress =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTedition =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTmonth =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTnote =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>

    OPTannote =&nbsp;&nbsp;&nbsp;&nbsp; {}<br>
    }</p>
    <hr>
    <p>@InBook{,<br>
    ALTauthor =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>

    ALTeditor =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    title =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    chapter =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    publisher =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>

    year =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTkey =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTvolume =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTnumber =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>

    OPTseries =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTtype =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTaddress =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTedition =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>

    OPTmonth =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTpages =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTnote =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTannote =&nbsp;&nbsp;&nbsp;&nbsp; {}<br>

    }</p>
    <hr>
    <p>@Proceedings{,<br>
    title =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    year =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>

    OPTkey =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTeditor =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTvolume =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTnumber =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>

    OPTseries =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTaddress =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTmonth =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTorganization = {},<br>

    OPTpublisher = {},<br>
    OPTnote =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTannote =&nbsp;&nbsp;&nbsp;&nbsp; {}<br>
    }</p>
    <hr>

    <p>@Book{,<br>
    ALTauthor =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    ALTeditor =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    title =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>

    publisher =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    year =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTkey =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTvolume =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>

    OPTnumber =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTseries =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTaddress =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTedition =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>

    OPTmonth =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTnote =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTannote =&nbsp;&nbsp;&nbsp;&nbsp; {}<br>
    }</p>

    <hr>
    <p>@Booklet{,<br>
    title =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTkey =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTauthor =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>

    OPThowpublished = {},<br>
    OPTaddress =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTmonth =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTyear =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>

    OPTnote =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTannote =&nbsp;&nbsp;&nbsp;&nbsp; {}<br>
    }</p>
    <hr>
    <p>@PhdThesis{,<br>

    author =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    title =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    school =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    year =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>

    OPTkey =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTtype =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTaddress =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTmonth =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>

    OPTnote =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTannote =&nbsp;&nbsp;&nbsp;&nbsp; {}<br>
    }</p>
    <hr>
    <p>@MastersThesis{,<br>

    author =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    title =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    school =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    year =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>

    OPTkey =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTtype =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTaddress =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTmonth =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>

    OPTnote =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTannote =&nbsp;&nbsp;&nbsp;&nbsp; {}<br>
    }</p>
    <hr>
    <p>@Manual{,<br>

    title =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTkey =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTauthor =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTorganization = {},<br>

    OPTaddress =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTedition =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTmonth =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTyear =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>

    OPTnote =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTannote =&nbsp;&nbsp;&nbsp;&nbsp; {}<br>
    }</p>
    <hr>
    <p>@Unpublished{,<br>

    author =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    title =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    note =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTkey =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>

    OPTmonth =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTyear =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTannote =&nbsp;&nbsp;&nbsp;&nbsp; {}<br>
    }</p>

    <hr>
    <p>@Misc{,<br>
    OPTkey =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTauthor =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTtitle =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>

    OPThowpublished = {},<br>
    OPTmonth =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTyear =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>
    OPTnote =&nbsp;&nbsp;&nbsp;&nbsp; {},<br>

    OPTannote =&nbsp;&nbsp;&nbsp;&nbsp; {}<br>
    }

</div>
<?php include($SITE_PATHS["SERV_INC"].'footer.inc'); ?>
