#!/bin/perl
my $logfile="setup-simpleca.log";
system("touch $logfile");

my ($glob) = glob("globus_simple_ca_*.tar.gz");
$glob =~ s#globus_simple_ca_(.{8})\.tar\.gz#$1#;
$simplecahash = $glob;

system("rpmbuild -ta globus_simple_ca*.tar.gz > $logfile 2>&1");
system("rpm -i '/root/rpmbuild/RPMS/noarch/globus-simple-ca*' > $logfile 2>&1");
system("grid-default-ca -ca $simplecahash > $logfile 2>&1");
system("chown myproxy /etc/grid-security/myproxy/ > $logfile 2>&1");

