#!/bin/perl
my ($glob) = glob("globus_simple_ca_*.tar.gz");
$glob =~ s#globus_simple_ca_(.{8})\.tar\.gz#$1#;
$simplecahash = $glob;

system("rpmbuild -ta globus_simple_ca*.tar.gz");
system("rpm -i '/root/rpmbuild/RPMS/noarch/globus-simple-ca*'");
system("grid-default-ca -ca $simplecahash");
system("chown myproxy /etc/grid-security/myproxy/");

