<div id="draft" align="center" style="background-color:#FFFF99; border:1px solid #ccc; padding: 5px; font-size: .85em; "> <p><strong>Tech Preview</strong><br /> This component is a Tech Preview for the GT 4.0 final distribution.
  As such, this documentation is not part of the GT 4.0 official documentation but is provided by the developer(s) to assist early adopters. Therefore, it may not conform to the guidelines for official documentation</p>

</div>
