<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://www.gridforum.org/namespaces/2003/03/gridWSDLExtensions/wsdl" 
             xmlns="http://schemas.xmlsoap.org/wsdl/">
  <import namespace="http://www.gridforum.org/namespaces/2003/03/gridWSDLExtensions" location="gwsdl_port_type.xsd"/>
</definitions>
