<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://www.gridforum.org/namespaces/2003/03/serviceData/wsdl" 
             xmlns="http://schemas.xmlsoap.org/wsdl/">
  <import namespace="http://www.gridforum.org/namespaces/2003/03/serviceData" location="ogsi_service_data.xsd"/>
</definitions>
