        <!--end div of content-->
      </div>
      <!--ending div of container-->
    </div>

<!--sidebar is commented out for GRIDS Center website
    <div id="sidebar">
      <ul>
        <li>FAQ<br />
            Site Index<br />
            Contact Us<br /><br /></li>
        <li><form method="post" action="http://tiger.mcs.anl.gov/htdig/cgi-bin/htsearch.cgi">
			<input type="hidden" name="config" value="globus" />
			<input type="hidden" name="exclude" value="mail_archive" />
			<font color="#6699ff"><b>Site Search:</b></font><br />
			<input type="text" name="words" size="20" maxlength="2033" value="" />
			</form> 
		</li>
      </ul>
    </div>
end of commented-out sidebar-->

    <div class="clearing">&nbsp;</div>
    <!--ending div of wrapper-->
  </div>
  <!--ending div of outer_wrapper-->
</div>

  <!-- FOOTER -->
  <!-- This is copied from the GRIDS Center FrontPage website at http://www.grids-center.org/. -->

  <div id="footer">
    <p class="panel">&copy;2004 GRIDS Center. All Rights Reserved.</p>
    <p class="panel"><a href="http://www.grids-center.org/site_map.asp">Site Map</a> | 
                     <a href="mailto:contact@grids-center.org">Contact</a></p>
  </div>

</body>
</html>
