<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" lang="en">

<head>
<title><?php echo $title; ?></title>
<!-- <link rel="shortcut icon" href="/images/favicon.ico"> -->
<!-- <link rel="icon" href="/images/favicon.ico"> -->
<meta http-equiv="Content-type" content="text/html;charset=UTF-8" />
<?php echo '<LINK href="'.$SITE_PATHS["WEB_CSS"].'grids_main.css" rel="stylesheet" type="text/css" />'; ?>
<?php echo '<LINK href="'.$SITE_PATHS["WEB_CSS"].'default.css" rel="stylesheet" type="text/css" />'; ?>
<?php echo '<LINK rel="stylesheet" type="text/css" href="'.$SITE_PATHS["WEB_ROOT"].'css/print.css" media="print" />'; ?>
</head>

<body class="<?php echo $section; ?>">

<div id="header"> 

  <!-- TOP BANNER -->
  <!-- This is copied from the GRIDS Center FrontPage website at http://www.grids-center.org/. -->
  
  <table border="0" cellpadding="0" cellspacing="0" width="795">
    <tr height="67">
      <td height="67" valign="bottom" align="left" width="263">
        <?php echo '<img src="'.$SITE_PATHS["WEB_IMG"].'grids-topleft.jpg" alt="GRIDS Center" border="0" 
                    width="263" height="67">'; ?></td>
      <td height="67" valign="top" align="right"><b><sub>Grid Research Integration Deployment and Support 
                                                 Center</sub></b></font>&nbsp;</td>
      <td width="190" height="67" valign="top" align="right"><a href="http://www.grids-center.org/">
        <?php echo '<img src="'.$SITE_PATHS["WEB_IMG"].'grids-logo.gif" alt="GRIDS Center" 
                    border="0" width="190" height="68">'; ?></a></td>
    </tr>
  </table>
  <table border="0" cellpadding="0" cellspacing="0" width="795">
    <tr height="32">
      <td width="795" height="32" valign="top" align="left">
        <?php echo '<img src="'.$SITE_PATHS["WEB_IMG"].'grids-topShim.gif" alt="----------------------" 
                    border="0" width="795" height="32">'; ?></a></td>
   </tr>
  </table>

</div>

<div id="outer_wrapper">
  <div id="wrapper">
    <div id="container">
      <div id="content">

