
		<div id="docbook_content_sidebar">
		 <h2 class="smalltitle">Software Links</h2>
           <dl class="leftColumn">
		   		<dt><a href="/toolkit/docs/4.2/4.2.1/Usage_Stats.html">Usage Statistics</a></dt>
				<dt><a href="/toolkit/docs/4.2/4.2.1/rn/">Release Notes</a></dt>
				<dt><a href="/toolkit/versioning.html">Versioning</a></dt>
				<dt><a href="/toolkit/downloads/">Downloads</a></dt>
				<dt><a href="/toolkit/advisories.html">Advisories</a></dt>
				<dt><a href="/toolkit/docs/4.2/4.2.1/licenses/">Licenses</a></dt>
				<dt><a href="http://dev.globus.org/wiki/How_to_contribute">CVS &amp; Dev Tools</a></dt>
			</dl>
			
		<h2 class="smalltitle">Getting Started</h2>
			<dl class="leftColumn">
			<!--
				<dt><a href="/toolkit/docs/4.2/4.2.1/doc_overview.html">Doc Structure</a></dt>
				-->
				<dt><a href="/toolkit/docs/4.2/4.2.1/key/">A Globus Primer</a></dt>
				<dt><a href="/toolkit/docs/4.2/4.2.1/globus_is_modular.html">Globus Is Modular!</a></dt>
				<dt><a href="/toolkit/docs/4.2/4.2.1/admin/install/">Installing GT</a></dt>
				<dt><a href="/toolkit/docs/4.2/4.2.1/admin/quickstart/">Quickstart</a></dt>
				<dt><a href="/toolkit/docs/4.2/4.2.1/admin/install/#gtadmin-platform">Platform Notes</a></dt>
				<dt><a href="/toolkit/docs/4.2/4.2.1/developer/">GT Developer's Guide</a></dt>
				<dt><a href="/toolkit/docs/4.2/4.2.1/user/">GT User's Guide</a></dt>
				<dt><a href="/toolkit/docs/4.2/4.2.1/mig/">Migrating Guides</a></dt>
			</dl>
			
		<h2 class="smalltitle">Reference</h2>
			<dl class="leftColumn">
				<dt><a href="/toolkit/docs/4.2/4.2.1/developer/#gt-bestpractices">Best Practices</a></dt>
				<dt><a href="/toolkit/docs/development/coding_guidelines.html">Coding Guidelines</a></dt>
				<dt><a href="/api/">API docs</a></dt>
				<dt><a href="/toolkit/docs/4.2/4.2.1/commands/">GT Commands</a></dt>
				<dt><a href="/toolkit/docs/4.2/4.2.1/user/#public-interfaces">Public Interfaces</a></dt>
				<dt><a href="/toolkit/docs/4.2/4.2.1/developer/#gt-rp">Resource Properties</a></dt>
				<dt><a href="/toolkit/docs/4.2/4.2.1/developer/#gt-samples">Samples</a></dt>
				<dt><a href="/toolkit/docs/4.2/4.2.1/glossary.html">Glossary</a></dt>
				<!--
				<dt>Performance Studies (coming soon)</dt>
				-->
			</dl>
		<h2 class="smalltitle">Manuals</h2>
		<h2 class="smalltitle"><a href="/toolkit/docs/4.2/4.2.1/common/">Common Runtime</a></h2>
			<dl class="leftColumn">
				<dt><a href="/toolkit/docs/4.2/4.2.1/common/javawscore/">Java WS Core</a></dt>
				<dt><a href="/toolkit/docs/4.2/4.2.1/common/cwscore/">C WS Core</a></dt>
				<dt><a href="/toolkit/docs/4.2/4.2.1/common/pythonwscore/">Python WS Core</a></dt>
				<dt><a href="/toolkit/docs/4.2/4.2.1/common/xio/">XIO</a></dt>
				<dt><a href="/toolkit/docs/4.2/4.2.1/common/javacog/">CoG jGlobus</a></dt>
				<dt><a href="/toolkit/docs/4.2/4.2.1/common/pyglobus/">pyGlobus</a></dt>
				<dt><a href="/toolkit/docs/4.2/4.2.1/common/ccommonlib/">C Common Libs</a></dt>
			</dl>
			
			<h2 class="smalltitle"><a href="/toolkit/docs/4.2/4.2.1/security/">Security</a></h2>
			<dl class="leftColumn">
				<dt><a href="/toolkit/docs/4.2/4.2.1/security/gsic/">GSI C</a></dt>
				<dt><a href="/toolkit/docs/4.2/4.2.1/common/javacog/">GSI Java</a></dt>
				<dt><a href="/toolkit/docs/4.2/4.2.1/security/wsaajava/">Java WS A&amp;A</a></dt>
				<dt><a href="/toolkit/docs/4.2/4.2.1/security/wsaac/">C WS A&amp;A</a></dt>
				<dt><a href="/toolkit/docs/4.2/4.2.1/security/cas/">CAS</a></dt>
				<dt><a href="/toolkit/docs/4.2/4.2.1/security/delegation/">Delegation Service</a></dt>
				<dt><a href="/toolkit/docs/4.2/4.2.1/security/myproxy/">MyProxy</a></dt>
				<dt><a href="/toolkit/docs/4.2/4.2.1/security/openssh/">GSI-OpenSSH</a></dt>
				<dt><a href="/toolkit/docs/4.2/4.2.1/security/simpleca/">SimpleCA</a></dt>
			</dl>
		
		<h2 class="smalltitle"><a href="/toolkit/docs/4.2/4.2.1/data/">Data Mgt</a></h2>
			<dl class="leftColumn">
				<dt><a href="/toolkit/docs/4.2/4.2.1/data/gridftp/">GridFTP</a></dt>
				<dt><a href="/toolkit/docs/4.2/4.2.1/data/rft/">RFT</a></dt>
				<dt><a href="/toolkit/docs/4.2/4.2.1/data/rls/">RLS</a></dt>
				<dt><a href="/toolkit/docs/4.2/4.2.1/data/wsrls/">WS RLS</a></dt>
				<dt><a href="/toolkit/docs/4.2/4.2.1/data/datarep/">DRS</a></dt>
			</dl>
		
		<h2 class="smalltitle"><a href="/toolkit/docs/4.2/4.2.1/info/">WS MDS</a></h2>
			<dl class="leftColumn">
				<dt><a href="/toolkit/docs/4.2/4.2.1/info/index/">Index Service</a></dt>
				<dt><a href="/toolkit/docs/4.2/4.2.1/info/trigger/">Trigger Service</a></dt>
				<dt><a href="/toolkit/docs/4.2/4.2.1/info/webmds/">WebMDS</a></dt>
				<dt><a href="/toolkit/docs/4.2/4.2.1/info/aggregator/">Aggregator Framework</a></dt>				
				<dt><a href="/toolkit/docs/4.2/4.2.1/info/usefulrp/">UsefulRP</a></dt>
				<dt><a href="/toolkit/docs/4.2/4.2.1/info/providers/">Info Providers</a></dt>
			</dl>
			
			<h2 class="smalltitle"><a href="/toolkit/docs/4.2/4.2.1/execution/">Execution Mgt</a></h2>
			<dl class="leftColumn">
				<dt><a href="/toolkit/docs/4.2/4.2.1/execution/gram4/">GRAM4</a></dt>
				<dt><a href="/toolkit/docs/4.2/4.2.1/execution/gridway/">GridWay</a></dt>
				<dt><a href="/toolkit/docs/4.2/4.2.1/execution/gram2/">GRAM2 (legacy)</a></dt>
			</dl>
	</div>
