        	<!-- content ENDS here -->
			</div>
			<p>&nbsp;</p>

    <div class="clearing">&nbsp;</div>
			<!-- container ENDS here-->
		</div>
<div id="footer">
  <hr class="first"/>
  <?php 
  include_once( "/mcs/www-unix.globus.org/toolkit/feedback.php" ); 
  ?>
  <p>Comments about the website?? <a href="mailto:webmaster@globus.org">webmaster@globus.org</a><br/>
  For our privacy statement, see: <a href="http://www.globus.org/privacy">http://www.globus.org/privacy</a></p>
  <p>Globus Project and Globus Toolkit are trademarks<br />
    held by the University of Chicago</p>
  <!--ending div of footer-->
  </div>