        	<!-- content ENDS here -->
			</div>
<!--			
			</td>
			</tr>
			</table>
			-->
			<p>&nbsp;</p>
		</div>
      <!--ending div of container-->
    </div>
    <div class="clearing">&nbsp;</div>
<!--ending div of wrapper-->
</div>
<div id="footer">
  <hr class="first"/>

  <p>Comments? <a href="mailto:webmaster@globus.org">webmaster@globus.org</a><br/>
  For our privacy statement, see: <a href="http://www.globus.org/privacy">http://www.globus.org/privacy</a></p>
  <p>Globus Project and Globus Toolkit are trademarks<br />
    held by the University of Chicago</p>
  <!--ending div of footer-->
  </div>