include ./BlogClientMakefile.include

all: create-blog add-blog-entry get-blog-entries destroy-blog

clean:
	-rm -f *.o create-blog add-blog-entry get-blog-entries destroy-blog

create-blog: create_blog.o
	$(GLOBUS_CC)  -o create-blog create_blog.o \
		$(GLOBUS_LDFLAGS) $(GLOBUS_LIBS) $(GLOBUS_PKG_LIBS)

create_blog.o: create_blog.c
	$(GLOBUS_CC) $(GLOBUS_CFLAGS) $(GLOBUS_INCLUDES) \
		-c -o create_blog.o create_blog.c

add-blog-entry: add_blog_entry.o
	$(GLOBUS_CC)  -o add-blog-entry add_blog_entry.o \
		$(GLOBUS_LDFLAGS) $(GLOBUS_LIBS) $(GLOBUS_PKG_LIBS)

add_blog_entry.o: add_blog_entry.c
	$(GLOBUS_CC) $(GLOBUS_CFLAGS) $(GLOBUS_INCLUDES) \
		-c -o add_blog_entry.o add_blog_entry.c

get-blog-entries: get_blog_entries.o
	$(GLOBUS_CC)  -o get-blog-entries get_blog_entries.o \
		$(GLOBUS_LDFLAGS) $(GLOBUS_LIBS) $(GLOBUS_PKG_LIBS)

get_blog_entries.o: get_blog_entries.c
	$(GLOBUS_CC) $(GLOBUS_CFLAGS) $(GLOBUS_INCLUDES) \
		-c -o get_blog_entries.o get_blog_entries.c

destroy-blog: destroy_blog.o
	$(GLOBUS_CC)  -o destroy-blog destroy_blog.o \
		$(GLOBUS_LDFLAGS) $(GLOBUS_LIBS) $(GLOBUS_PKG_LIBS)

destroy_blog.o: destroy_blog.c
	$(GLOBUS_CC) $(GLOBUS_CFLAGS) $(GLOBUS_INCLUDES) \
		-c -o destroy_blog.o destroy_blog.c
