default: all

gtAdmin.pdf: \
        quickstart/gtQuickstart.pdf \
        install/installingGT.pdf \
        install/installationAppendix.pdf

PDF_FILES=gtAdmin.pdf
SUBDIRS=install quickstart

TOPDIR=..
include $(TOPDIR)/rules.mk
