<?xml version="1.0" encoding="UTF-8"?>
<definitions name="OGSIHandleResolver" targetNamespace="http://www.gridforum.org/namespaces/2003/03/OGSI/service" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ogsibinding="http://www.gridforum.org/namespaces/2003/03/OGSI/bindings" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"><import location="ogsi_bindings.wsdl" namespace="http://www.gridforum.org/namespaces/2003/03/OGSI/bindings"/><service name="OGSIHandleResolverService"><port binding="ogsibinding:HandleResolverSOAPBinding" name="HandleResolverPort"><soap:address location="http://localhost:8080/ogsa/services/"/></port></service></definitions>

