<html>
<head><meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<?
   if (strlen($title) == 0) {
      print("<title>MDS Information Providers</title>\n");
   } else {
      print("<title>$title</title>\n");
   }
?>
</head>
<body bgproperties="fixed" bgcolor="#FFFFFF" link="0000FF" alink="#0000FF" vlink="#0000FF">
<br><hr><br>
<font face="Verdana,Arial" size="2" color="#000000">
