all:
	xsltproc --stringparam chunk.section.depth 0 \
	  /usr/share/sgml/docbook/xsl-stylesheets-1.49-1/html/chunk.xsl admin.xml
rh9:
	xsltproc --stringparam chunk.section.depth 0 \
          /usr/share/sgml/docbook/xsl-stylesheets-1.58.1-2/html/chunk.xsl admin.xml
