        	<!-- content ENDS here -->
			</div>
			<p>&nbsp;</p>

    <div class="clearing">&nbsp;</div>
			<!-- container ENDS here-->
		</div>
<div id="footer">
  <hr class="first"/>

  <p>Comments? <a href="mailto:webmaster@globus.org">webmaster@globus.org</a></p>
  <p>Globus Project and Globus Toolkit are trademarks<br />
    held by the University of Chicago</p>
  <!--ending div of footer-->
  </div>