     <p><img src="<?=$SITE_PATHS["WEB_ALLIANCE"]."impact/ag-desktop2.jpg"; ?>" 
             alt="Using the Access Grid" width=266 height=186 /></p>
     <p>Scientists in the 
        <a href="http://www.fusiongrid.org/">National Fusion Collaboratory</a> 
        are learning to use the Access Grid and Globus Web services to 
        <a href="<?=$SITE_PATHS["WEB_ALLIANCE"]."publications/papers/clade_submitted_corrected.pdf"; ?>">participate 
        remotely in pulsed plasma fusion experiments</a>. The remote interface provides 
        sensor readings, data analysis, audio, and video available in the 
        control room and allows the team to discuss what is happening.  
        The <a href="http://www.accessgrid.org/">Access Grid</a> is integrated 
        with Grid services and applications
        using the Globus Toolkit's security and communication libraries.</p>
        
