     <p><img src="<?=$SITE_PATHS["WEB_ALLIANCE"]."impact/AG-bigroom.jpg";  ?>" 
             alt="Hurricane Isabel, Sept. 2003" width=266 height=172 /></p>
     <p>The Access Grid is a powerful way for distributed project teams to 
        work together interactively on scientific activities. For example,
        the National Fusion Grid project uses Access Grid and Globus Toolkit
        Web services to allow scientists to participate in experiments 
        remotely, giving them a sense of being in the control room.</p>
        
