     <p><img src="<?=$SITE_PATHS["WEB_ALLIANCE"]."impact/AG-bigroom.jpg";  ?>" 
             alt="Hurricane Isabel, Sept. 2003" width=266 height=172 /></p>
     <p>The <a href="http://www.accessgrid.org/">Access Grid</a> is a powerful 
        way to bring distributed teams together to work on scientific challenges. 
        For example,
        scientists in the National Fusion Collaboratory are learning to use 
        the Access Grid and Globus Web services to 
        <a href="<?=$SITE_PATHS["WEB_ALLIANCE"]."publications/papers/clade_submitted_corrected.pdf"; ?>">participate 
        remotely in pulsed plasma fusion experiments</a>. The remote interface provides 
        sensor readings, data analysis, audio, and video available in the 
        control room and allows the team to discuss what is happening.  
        The Access Grid is integrated with Grid services and applications
        using the Globus Toolkit's security and communication libraries.</p>
        
