     <p><img src="<?=$SITE_PATHS["WEB_ALLIANCE"]."impact/arterial_tree.jpg"; ?>" 
             alt="Arterial tree, (c) 2005 The University of Chicago/Argonne National Laboratory" /></p>
     <p>Computational scientists at Brown University are using the Globus Toolkit 
        and MPICH-G2 to simulate the flow of blood through human arteries.
        This image, prepared at Argonne National Laboratory, shows
        velocity (red arrows) and pressure (surface color) within a branched,
        three-dimensional arterial structure. The simulation was conducted using
        <a href="http://www.cfm.brown.edu/people/tcew/nektar.html">Nektar</a> 
        (software developed at Brown University) and was the first high-performance 
        simulation to run in a distributed fashion using multiple 
        <a href="http://www.teragrid.org/">TeraGrid</a> sites.
        <i>&copy; 2005 The University of Chicago/Argonne National Laboratory</i>.</p>
