     <p><img src="<?=$SITE_PATHS["WEB_ALLIANCE"]."impact/arterial-tree.jpg"; ?>" 
             alt="Arterial tree, (c) 2005 The University of Chicago/Argonne National Laboratory" /></p>
     <p>Computational scientists at Brown University used the Globus Toolkit 
        and MPICH-G2 to simulate the flow of blood through human arteries.
        This image, prepared at Argonne National Laboratory, shows
        velocity (arrows) and pressure (isosurfaces) within a branched,
        three-dimensional arterial structure. The simulation was conducted using
        <a href="http://www.cfm.brown.edu/people/tcew/nektar.html">Nektar</a> 
        (simulation software developed at Brown University) 
        and was run on distributed computational systems on the 
        <a href="http://www.teragrid.org/">TeraGrid</a>.
        <i>&copy; The University of Chicago/Argonne National Laboratory</i>.</p>
