     <p><img src="<?=$SITE_PATHS["WEB_ALLIANCE"]."impact/birthday.gif"; ?>" 
             alt="GT is 10 years old!" /></p>
     <p><b>Come celebrate with us!</b> In appreciation of your support of all things 
           Globus over the past decade, you are cordially invited to the 
           <a href="http://www.globusworld.org/">Globus 10th 
           Birthday Party</a> at GlobusWORLD / GridWorld 2006.</p>


