     <p><img src="<?=$SITE_PATHS["WEB_ALLIANCE"]."impact/birthday.gif"; ?>" 
             alt="GT is 10 years old!" /></p>
     <p><b>Come celebrate with us!</b> In appreciation of your support of all things 
           Globus over the past decade, you are cordially invited to the Globus 10th 
           Birthday Party at GlobusWORLD / GridWorld 2006.<br><br>
           <b>When:</b> Monday, September 11, 2006 - 7:00pm, immediatly following Ian Foster's Globus State of the Union Keynote.<br><br>

<b>Where:</b>
Washington, D.C. Convention Center Consourse, in the center of the GridWorld conference activity.</p>

