     <p><img src="<?=$SITE_PATHS["WEB_ALLIANCE"]."impact/gravitywaves.jpg"; ?>" 
             alt="Gravity waves" /></p>
     <p>Physicists used the Globus Toolkit and MPICH-G2 to harness the power of multiple 
        supercomputers to simulate the gravitational effects of black hole 
        collisions.  The team, which included researchers from Argonne 
        National Laboratory, the University of Chicago, Northern Illinois 
        University, and the Max Planck Institute for Gravitational Physics 
        in Germany, was awarded a prestigious 
        <a href="http://www-unix.mcs.anl.gov/~pieper/SUCCESS/gordon01.html">Gordon 
        Bell prize</a> for its work. Image courtesy of 
        <a href="http://www.aei-potsdam.mpg.de/">Max Planck Institute for 
        Gravitational Physics</a>.</p>
