     <p><img src="<?=$SITE_PATHS["WEB_ALLIANCE"]."impact/isabel-1.jpg"; ?>" 
             alt="Hurricane Isabel, Sept. 2003" /></p>
     <p>The Globus Toolkit supports scientific data visualization on the 
        <a href="http://www.teragrid.org/">TeraGrid</a>.  
        This image is part of a sequence that reveals the progression of 
        Hurricane Isabel in September 2003.  
        A desktop application uses the Globus Toolkit to launch parallel 
        visualization tasks on multiple TeraGrid graphics nodes.
        The appication allows users to connect to and interact with these
        tasks.
        Data provided by the 
        <a href="http://www.ncar.ucar.edu/">National Center for Atmospheric Research</a>.</p>
