     <p><img src="<?=$SITE_PATHS["WEB_ALLIANCE"]."impact/OpenSourceColor.jpg"; ?>" 
             alt="Open Source Grid and Cluster Conference" width=266 height=66 /></p>
     <p>Join Users, Administrators, and Developers of Open Source Grid and
Cluster Software from across the globe at this unique event.</p>

<p>Open Source Grid &amp; Cluster Conference 2008<br>
May 12-16, 2008<br>
Marriott City Center<br>
Oakland, California, USA<br>

For more information visit <a href="http://www.OpenSourceGridCluster.org/">www.OpenSourceGridCluster.org</a></p>
        
