     <p><img src="<?=$SITE_PATHS["WEB_ALLIANCE"]."impact/scec-terashake-x.gif"; ?>" 
             width=266 height=184 alt="SCEC Terashake" /></p>
     <p>The <a href="http://www.scec.org/">Southern California Earthquake 
        Collaboratory</a> uses Globus software to visualize earthquake simulation data.
        Scientists simulate earthquakes by calculating the effect of shock 
        waves as they propagate through various layers of a geological model.  
        This image shows earth movement from San Joaquin Valley 
        CA, to Mexico, across the Los Angeles basin, moments after a simulated 
        rupture.  Blue and red lobes depict waves moving in opposite directions 
        along the fault.</p>
