     <p><img src="<?=$SITE_PATHS["WEB_ALLIANCE"]."impact/scec-dfm-pair.jpg"; ?>" 
             width=266 height=200 alt="Earthquake visualization" /></p>
     <p>The <a href="http://www.scec.org/">Southern California Earthquake 
        Collaboratory</a> uses Globus software to visualize earthquake simulation data.
        Scientists simulate earthquakes by 
        calculating the effect of shock waves as they propagate through 
        various layers of a geological model. This image shows the velocity 
        of motion from a simulated earthquake through a uniform earth. The 
        image is provided in stereo so that it can be viewed in 3D.</p>
