     <p><img src="<?=$SITE_PATHS["WEB_ALLIANCE"]."impact/scec-terashake-x.gif"; ?>" 
             width=266 height=184 alt="SCEC Terashake" /></p>
     <p>The <a href="http://www.scec.org/">Southern California Earthquake 
        Collaboratory</a> uses Globus software to visualize earthquake simulation data.
        Scientists simulate earthquakes by calculating the effect of shock 
        waves as they propagate through various layers of a geological model.  
        SCEC simulations cover a very large space with very high resolution and can 
        generate up to 40TB of data per simulation run.
        This image shows earth movement from San Joaquin Valley 
        CA, to Mexico, across the Los Angeles basin, moments after a simulated 
        rupture.  Blue and red lobes depict motion in opposite directions caused by
        shock waves along the fault.</p>
