     <p><img src="<?=$SITE_PATHS["WEB_ALLIANCE"]."impact/sea-ice.jpg"; ?>" 
             alt="Earth System Grid Data" width=266 height=241 /></p>
     <p>Scientists in the 
        <a href="http://www.earthsystemgrid.org/">Earth System Grid (ESG)</a> 
        are producing, archiving, and providing access to climate data that
        advances our understanding of global climate change. This image displays data from
        ESG and shows sea ice extent (white/gray), sea ice motion, sea surface 
        temperatures (colors), and atmospheric sea level pressure (contours). 
        ESG uses Globus software for 
        <a href="<?=$SITE_PATHS["WEB_SOLUTIONS"]."purse/"; ?>">security</a>, 
        data movement, and 
        <a href="<?=$SITE_PATHS["WEB_SOLUTIONS"]."system_monitoring/"; ?>">system monitoring</a>. 
        Image provided by <a href="http://www.ucar.edu/">UCAR</a>.</p>
        
