<div id="draft" align="center" style="background-color:#FFFF99; border:1px solid #ccc; padding: 5px; font-size: .85em; "> <p><strong>DRAFT</strong><br /> This page is a work-in-progress for the GT 4.0 final documentation.
  For snapshots of these docs per development release (for example, <a href="../../3.9.3/">3.9.3</a>) please
  see the <a href="../../">Development Documents page</a>.</p>
</div>
