        
	
	<div id="docbook_content_sidebar">
		 <h2 class="smalltitle">Software Links</h2>
           <dl class="leftColumn">
		   		<dt><a href="/toolkit/docs/5.0/5.0.5/Usage_Stats.html">Usage Statistics</a></dt>
				<dt><a href="/toolkit/docs/5.0/5.0.5/rn/">Release Notes</a></dt>
				<dt><a href="/toolkit/versioning.html">Versioning</a></dt>
				<dt><a href="/toolkit/downloads/">Downloads</a></dt>
				<dt><a href="/toolkit/advisories.html">Advisories</a></dt>
				<dt><a href="/toolkit/docs/5.0/5.0.5/licenses/">Licenses</a></dt>
				<dt><a href="http://dev.globus.org/wiki/How_to_contribute">CVS &amp; Dev Tools</a></dt>
			</dl>
			
		<h2 class="smalltitle">Getting Started</h2>
			<dl class="leftColumn">
			<!--
				<dt><a href="/toolkit/docs/5.0/5.0.5/doc_overview.html">Doc Structure</a></dt>
				-->
				<dt><a href="/toolkit/docs/5.0/5.0.5/globus_is_modular.html">Globus Is Modular!</a></dt>
				<dt><a href="/toolkit/docs/5.0/5.0.5/admin/install/">Installing GT</a></dt>
				<dt><a href="/toolkit/docs/5.0/5.0.5/admin/quickstart/">Quickstart</a></dt>
				<dt><a href="/toolkit/docs/5.0/5.0.5/admin/install/#gtadmin-platform">Platform Notes</a></dt>
				<dt><a href="/toolkit/docs/5.0/5.0.5/developer/">GT Developer's Guide</a></dt>
				<dt><a href="/toolkit/docs/5.0/5.0.5/user/">GT User's Guide</a></dt>
				<dt><a href="/toolkit/docs/5.0/5.0.5/mig/">Migrating Guides</a></dt>
			</dl>
			
		<h2 class="smalltitle">Components</h2>
			<h2 class="smalltitle"></h2>
			<dl class="leftColumn">
			<dt><a href="/toolkit/docs/5.0/5.0.5/data/">Data Mgt</a>
				<dd><a href="/toolkit/docs/5.0/5.0.5/data/gridftp/">GridFTP</a></dd>
				<dd><a href="/toolkit/docs/5.0/5.0.5/data/rls/">RLS</a></dd>
				</dt>
			<dt><a href="/toolkit/docs/5.0/5.0.5/execution/">Execution Mgt</a>
			<dd><a href="/toolkit/docs/5.0/5.0.5/execution/gram5/">GRAM5</a></dd>
			</dt>
			<dt><a href="/toolkit/docs/5.0/5.0.5/security/">Security</a>
			<dd><a href="/toolkit/docs/5.0/5.0.5/security/gsic/">GSI C</a></dd>
				<dd><a href="/toolkit/docs/5.0/5.0.5/security/myproxy/">MyProxy</a></dd>
				<dd><a href="/toolkit/docs/5.0/5.0.5/security/openssh/">GSI-OpenSSH</a></dd>
				<dd><a href="/toolkit/docs/5.0/5.0.5/security/simpleca/">SimpleCA</a></dd>
			</dt>
			<dt><a href="/toolkit/docs/5.0/5.0.5/common/">Common Runtime</a>
			
				<dd><a href="/toolkit/docs/5.0/5.0.5/common/xio/">XIO</a></dd>
				<dd><a href="/toolkit/docs/5.0/5.0.5/common/ccommonlib/">C Common Libs</a></dd>
			</dt>
			</dl>
	
			
		<h2 class="smalltitle">Reference</h2>
			<dl class="leftColumn">
			<!--	<dt><a href="/toolkit/docs/5.0/5.0.5/developer/#gt-bestpractices">Best Practices</a></dt> -->
				<dt><a href="/toolkit/docs/development/coding_guidelines.html">Coding Guidelines</a></dt>
				<dt><a href="/api/">API docs</a></dt>
				<dt><a href="/toolkit/docs/5.0/5.0.5/commands/">GT Commands</a></dt>
				<dt><a href="/toolkit/docs/5.0/5.0.5/user/#public-interfaces">Public Interfaces</a></dt>
				<dt><a href="/toolkit/docs/5.0/5.0.5/index.html#glossary">Glossary</a></dt>
			</dl>
	
	</div>
