#!/usr/bin/env perl

# system( "java LogParser 2.2.2 09-30-2002" );

# 31 - jan, mar, may, jul, aug, oct, dec
# 30 -        apr,  jun,     sep,  nov

foreach $version qw( 1.1.4 )
{
    foreach $year ( 2003 )
    {
        foreach $month ( 4,5,6,7 )
        {
            if ( ( $month == 2 ) or
                ( $month == 4 ) or
                ( $month == 6 ) or
                ( $month == 9 ) or
                ( $month == 11 ) )
            {
                $days = 30;
            }
            else 
            {
                $days = 31;
            }

            foreach $day ( 1..$days )
            {
                print "command -> java LogParser $version $month $day $year\n";
                system( "java LogParser $version $month $day $year" );
            }
        }
    }
}
