#!/usr/bin/env perl

# system( "java LogParser 2.2.2 09-30-2002" );

# 31 - jan, mar, may, jul, aug, oct, dec
# 30 -        apr,  jun,     sep,  nov

foreach $version qw( 1.1.4 )
{
    foreach $year ( 2003 )
    {
        foreach $month ( 2,3 )
        {
            $days = 31;
            if ( $month == 2 )
            {
                $days = 29;
            }
            foreach $day ( 1..$days )
            {
                if ( ( $day < 22 ) and ( $month == 2 ) )
                {
                    next;
                }
                print "command -> java LogParser $version $month $day $year\n";
                system( "java LogParser $version $month $day $year" );
            }
        }
    }
}
