
      <ul>
        <li><a href="http://www-unix.globus.org/r3/alliance/activities/index.php">Activities</a></li>
        <li><a href="http://www-unix.globus.org/r3/alliance/news/index.php">News &amp; Archive</a></li>
        <li><a href="http://www-unix.globus.org/r3/alliance/participants.php">Participants</a></li>
        <li><a href="http://www-unix.globus.org/r3/alliance/sponsors.php">Sponsors</a></li>
        <li><a href="http://www-unix.globus.org/r3/alliance/employment/">Job Opportunties</a></li>
      </ul>
