      <ul>
        <li><a href="docs/index.php">Release Manuals</a>
			<ul>
				<li><a href="#">3.2</a></li>
				<li><a href="#">3.0</a></li>
				<li><a href="#">Development</a><li>
			</ul>
		</li>
        <li><a href="#">FAQs</a>
			<ul>
				<li><a href="#">3.2</a></li>
				<li><a href="#">3.0</a></li>
				<li><a href="#">Development</a><li>
			</ul>
		</li>
        <li><a href="#">Glossary</a>
			<ul>
				<li><a href="#">3.2</a></li>
				<li><a href="#">3.0</a></li>
				<li><a href="#">Development</a><li>
			</ul>
		</li>
      </ul>