        <!--end div of content-->
      </div>
      <!--ending div of container-->
    </div>

    <div class="clearing">&nbsp;</div>
    <!--ending div of wrapper-->
  </div>

<div id="footer">
  <hr class="first"/>
  <p class="panel">For questions or feedback about this website: 
     <a href="mailto:webmaster@globus.org">webmaster@globus.org</a><br>
   For technical support or questions about Globus software, visit our 
     <a href="<?=$SITE_PATHS["WEB_TOOLKIT"]."support.html"; ?>">technical support</a> page.</p>
  <p class="panel">Globus, Globus Alliance, and Globus Toolkit are trademarks<br>
    held by the University of Chicago.</p>
  <!--ending div of footer-->
</div>

<script src="http://www.google-analytics.com/urchin.js" type="text/javascript">
</script>
<script type="text/javascript">
_uacct = "UA-726125-2";
urchinTracker();
</script> 

</body>

</html>
