        	<!-- content ENDS here -->
			<p>&nbsp;</p>
		</div>
      <!--ending div of container-->
    </div>
    <div class="clearing">&nbsp;</div>
    <!--ending div of wrapper-->
  </div>
<div id="footer">
  <hr class="first"/>

  <p>Comments?<br />
  For questions or feedback about this website:  <a href="mailto:webmaster@globus.org">webmaster@globus.org</a><br />
  For technical support or questions about Globus software, visit our <a href="http://www.globus.org/toolkit/support.html">technical
support</a> page.
</p>
  <p>Globus Project and Globus Toolkit are trademarks<br />
    held by the University of Chicago</p>
  <!--ending div of footer-->
</div>
</body>
</html>
