        	<!-- content ENDS here -->
			<p>&nbsp;</p>
		</div>
      <!--ending div of container-->
    </div>
    <div class="clearing">&nbsp;</div>
    <!--ending div of wrapper-->
  </div>

  <hr class="first"/>
  <br>
	<div align="justify" class="docblurb" id="blurb">
    <p>This document is a work-in-progress and applies to this development release.  The latest drafts of docs can be found in the <a href="http://www-unix.globus.org/toolkit/docs/development/docmap.html">GT4 Documentation Roadmap</a>. <br><br>
	You are strongly encouraged to file bugs for both the development documentation and software on our <a href="http://www-unix.globus.org/toolkit/bugzilla.html">Bugzilla page</a>. <br><br>
Consider joining a new discussion list called <strong>gt4-friends@globus.org</strong> to exchange ideas about GT4 development, such as documentation and testing.  To subscribe to gt4-friends, send an email to <a href="mailto:majordomo@globus.org">majordomo@globus.org</a> which contains the words "subscribe gt4-friends" in the message body.  You must subscribe to gt4-friends in order to send mail to it. We appreciate your participation.</div>
<div id="footer">
    <p>Comments?<br />
  For questions or feedback about this website:  <a href="mailto:webmaster@globus.org">webmaster@globus.org</a><br />
  For technical support or questions about Globus software, visit our <a href="http://www.globus.org/toolkit/support.html">technical
support</a> page.
</p>
  <p>Globus Project and Globus Toolkit are trademarks<br />
    held by the University of Chicago</p>
  <!--ending div of footer-->
</div>
</body>
</html>
