
      <ul>
        <li><?php echo '<a href="'.$SITE_PATHS["WEB_SOFTWARE"].'ecology.php">'; ?>An Ecosystem of Grid Components</a></li>
        <li><?php echo '<a href="'.$SITE_PATHS["WEB_SOFTWARE"].'role-of-gt.php">'; ?>Role of the Globus Toolkit</a></li>
        <li><?php echo '<a href="'.$SITE_PATHS["WEB_SOFTWARE"].'security-components.php">'; ?>Security</a></li>
        <li><?php echo '<a href="'.$SITE_PATHS["WEB_SOFTWARE"].'monitoring-components.php">'; ?>Monitoring and Discovery</a></li>
        <li><?php echo '<a href="'.$SITE_PATHS["WEB_SOFTWARE"].'computation-components.php">'; ?>Computation</a></li>
        <li><?php echo '<a href="'.$SITE_PATHS["WEB_SOFTWARE"].'data-components.php">'; ?>Data</a></li>
        <li><?php echo '<a href="'.$SITE_PATHS["WEB_SOFTWARE"].'collaboration-components.php">'; ?>Collaboration</a></li>
        <li><?php echo '<a href="'.$SITE_PATHS["WEB_SOFTWARE"].'packaging-tools-and-dist.php">'; ?>Packaging and Distribution</a></li>
      </ul>
