-->
<div id="left">

      <ul>
        <li><a href="http://www.grids-center.org/">Home</a></li>
        <li><a href="http://www.grids-center.org/grids/index.asp">GRIDS Essentials</a></li>
        <li><?php echo '<a href="'.$SITE_PATHS["WEB_SOFTWARE"].'">'; ?>Grid Ecosystem</a></li>
      </ul>
      <ul>
        <ul>
        <li><?php echo '<a href="'.$SITE_PATHS["WEB_SOFTWARE"].'ecology.php">'; ?>An Ecosystem of Grid Components</a></li>
        <li><?php echo '<a href="'.$SITE_PATHS["WEB_SOFTWARE"].'security/">'; ?>Security</a></li>
        <li><?php echo '<a href="'.$SITE_PATHS["WEB_SOFTWARE"].'monitoring/">'; ?>Monitoring & Discovery</a></li>
        <li><?php echo '<a href="'.$SITE_PATHS["WEB_SOFTWARE"].'computation/">'; ?>Computation</a></li>
        <li><?php echo '<a href="'.$SITE_PATHS["WEB_SOFTWARE"].'data/">'; ?>Data</a></li>
        <li><?php echo '<a href="'.$SITE_PATHS["WEB_SOFTWARE"].'collaboration/">'; ?>Collaboration</a></li>
        <li><?php echo '<a href="'.$SITE_PATHS["WEB_SOFTWARE"].'packaging/">'; ?>Packaging & Distribution</a></li>
        <li><a href="<?=$SITE_PATHS["WEB_SOLUTIONS"]; ?>">Grid Solutions</a></li>
        </ul>
      </ul>
      <ul>
        <li><a href="http://www.grids-center.org/train/index.asp">Training & Support</a></li>
        <li><a href="http://www.grids-center.org/news/index.asp">News & Outreach</a></li>
        <li><a href="http://www.grids-center.org/downloads/index.asp">Downloads</a></li>
      </ul>
</div>
<!--
