
      <ul>
        <li><a href="<?=$SITE_PATHS["WEB_SOLUTIONS"]."overview.php"; ?>">Overview</a></li>
        <li><a href="<?=$SITE_PATHS["WEB_SOLUTIONS"]."purse/"; ?>">PURSE</a></li>
        <li><a href="<?=$SITE_PATHS["WEB_SOLUTIONS"]."vomrs/"; ?>">VOMRS</a></li>
        <li><a href="<?=$SITE_PATHS["WEB_SOLUTIONS"]."esg-monitoring/"; ?>">ESG Monitoring System</a></li>
        <li><a href="<?=$SITE_PATHS["WEB_SOLUTIONS"]."tgcp/"; ?>">TeraGrid TGCP Tool</a></li>
        <li><a href="<?=$SITE_PATHS["WEB_SOLUTIONS"]."ldr/"; ?>">Lightweight Data Replicator</a></li>
        <li><a href="<?=$SITE_PATHS["WEB_SOLUTIONS"]."pegasus/"; ?>">Pegasus</a></li>
        <li><a href="<?=$SITE_PATHS["WEB_SOLUTIONS"]."striped-gridftp/"; ?>">Striped GridFTP Server</a></li>
      </ul>
