-->
<div id="left">

      <ul>
        <li><a href="http://www.grids-center.org/">Home</a></li>
        <li><a href="http://www.grids-center.org/grids/index.asp">GRIDS Essentials</a></li>
        <li><?php echo '<a href="'.$SITE_PATHS["WEB_SOFTWARE"].'">'; ?>Grid Ecosystem</a></li>
      </ul>
      <ul>
        <ul>
        <li><?php echo '<a href="'.$SITE_PATHS["WEB_SOFTWARE"].'ecology.php">'; ?>An Ecosystem of Grid Components</a></li>
        <li><?php echo '<a href="'.$SITE_PATHS["WEB_SOFTWARE"].'security-components.php">'; ?>Security</a></li>
        <li><?php echo '<a href="'.$SITE_PATHS["WEB_SOFTWARE"].'monitoring-components.php">'; ?>Monitoring & Discovery</a></li>
        <li><?php echo '<a href="'.$SITE_PATHS["WEB_SOFTWARE"].'computation-components.php">'; ?>Computation</a></li>
        <li><?php echo '<a href="'.$SITE_PATHS["WEB_SOFTWARE"].'data-components.php">'; ?>Data</a></li>
        <li><?php echo '<a href="'.$SITE_PATHS["WEB_SOFTWARE"].'collaboration-components.php">'; ?>Collaboration</a></li>
        <li><?php echo '<a href="'.$SITE_PATHS["WEB_SOFTWARE"].'packaging-tools-and-dist.php">'; ?>Packaging & Distribution</a></li>
        <li><a href="<?=$SITE_PATHS["WEB_SOLUTIONS"]; ?>">Grid Solutions</a></li>
        </ul>
      </ul>
      <ul>
        <li><a href="http://www.grids-center.org/train/index.asp">Training & Support</a></li>
        <li><a href="http://www.grids-center.org/news/index.asp">News & Outreach</a></li>
        <li><a href="http://www.grids-center.org/downloads/index.asp">Downloads</a></li>
      </ul>
</div>
<!--
