
<div id="headerlinks">

<br />
<a href="http://www.globus.org/faq.php">FAQ</a><br />
<a href="http://www.globus.org/site_map.php">Site Map</a><br />
<a href="http://dev.globus.org/wiki/Mailing_Lists">Contact Us</a>
</div>

<div id="header"> <div align="left"> 
<img src="http://www.globus.org/toolkit/images/globustoolkit.gif" alt="The Globus Toolkit" width="160" height="76" /></div>


<ul id="menu">
<li id="nav-1"><a href="http://www.globus.org/">Home</a></li>

<li id="nav-2"><a href="http://www.globus.org/alliance/">Globus Alliance</a></li>
<li id="nav-3"><a href="http://www.globus.org/toolkit/">Globus Toolkit</a></li>
<li id="nav-4"><a href="http://www.globus.org/grid_software/">Grid Software</a></li>
<li id="nav-5"><a href="http://www.globus.org/solutions/">Grid Solutions</a></li>
<li id="nav-6"><a href="https://dev.globus.org/wiki/Welcome">dev.globus</a></li>
<!-- end of navigation list -->

</ul>


<table class="navbartable" width="100%">
<tr>
<th>
<a href='/'>Home</a> -&gt; <a href='/toolkit/'>Toolkit</a> -&gt; <a href='/toolkit/docs/'>Docs</a> -&gt; <a href='/toolkit/docs/4.0/'>4.0</a> -&gt; <a href='/toolkit/docs/4.0/security/'>Security</a> -&gt; <a href='/toolkit/docs/4.0/security/authzframe/'>Authzframe</a> 
</th>

<td>

<form method="GET" name="GlobusSearchForm"  
onSubmit="GlobusSubmit()">
<input type="radio" name="domain" value="nomail"  
checked>&nbsp;Website&nbsp;
<input type="radio" name="domain" value="mail">&nbsp;Email Lists&nbsp;
Search:&nbsp;<input type="text" name="qinit" size="20"  
maxlength="200" value="" />
<input type="hidden" name="cof" VALUE="S:http://www.globus.org/;VLC:#cccccc;AH:center;BGC:#ffffff;LH:76;LC:#003390;L:http://www.globus.org/img/globusalliance-nourl.gif;ALC:#003390;LW:170;T:#000000;AWFID:fb67b77f3237ebb9;">
<input type="hidden" name="domains" value="www.globus.org">

<br />
<input type="hidden" name="sitesearch" value="www.globus.org">
<input type="hidden" name="q" value="">
</form>
</td>
</tr>

</table>

</div>

<div id="wrapper">
<div id="container">
<div id="content">
<!-- content STARTS here -->