<wsdl:definitions name="BlogWSDL" 
                  targetNamespace="http://globus.org/blog/service" 
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
                  xmlns:binding="http://globus.org/blog/bindings">

  <wsdl:import namespace="http://globus.org/blog/bindings" 
               location="blog_bindings.wsdl"/>

  <wsdl:service name="BlogService">
    <wsdl:port name="BlogPortTypePort" 
               binding="binding:BlogPortTypeSOAPBinding">
      <soap:address location="http://localhost:8080/wsrf/services/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
