<div id="draft" align="center" style="background-color:#FFFF99; border:1px solid #ccc; padding: 5px; font-size: .85em; "> <p><strong>DRAFT</strong><br /> This page is a work-in-progress for the GT 4.0 final documentation.
  For snapshots of these docs per development release (for example, <a href="http://www-unix.globus.org/toolkit/docs/development/3.9.4/">3.9.4</a>) please
  see the <a href="http://www-unix.globus.org/toolkit/docs/development/">Development Documents page</a>.</p>
  <p>This is for internal use only; external users read at your own risk.</p>
</div>
